### PR TITLE
Added linkedin

### PR DESCRIPTION
**Pull request by Kanagaraj5463**

### CODE REVIEW

**Review by bharatbalajid — APPROVED** [review]

**Review by bharatbalajid — APPROVED** [review]

**Review by bharatbalajid — APPROVED** [review]
Added

**Comment by Kanagaraj5463** [comment]
Merge the request

**Review by bharatbalajid — APPROVED** [review]

**Comment by Kanagaraj5463** [comment]
Great!

**Comment by Kanagaraj5463** [comment]
Line no 36 is my change 
`<br><a href="https://www.linkedin.com/in/bharat-balaji-d-67913b20b"></a>`

**Comment by Kanagaraj5463** [comment]
seems to be good at desktop view

**Pull request merged**
